version: '3.1'

services:
  pgdb:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: BO7ZdJ49p
    ports:
      - 5439:5432
  api:
    image: api_mj
    build: ./
    restart: always
    environment:
      DB_HOST: host.docker.internal
      DB_NAME: postgres
      DB_PASSWORD: BO7ZdJ49p
      DB_PORT: 5439
      DB_USER: postgres
    ports:
      - 8000:8000
    depends_on:
      - pgdb
networks:
  host:
    external: true